//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_CodeFirst
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class marketplace_fermieriEntities : DbContext

       {
        public marketplace_fermieriEntities()
            : base("name=marketplace_fermieriEntities")
        {
            //this.Configuration.LazyLoadingEnabled = false;//for lazy loading
        }

        //protected override void OnModelCreating(DbModelBuilder modelBuilder)
        //{
        //    throw new UnintentionalCodeFirstException();
        //}

        public virtual DbSet<clienti> clienti { get; set; }
        public virtual DbSet<comenzi> comenzi { get; set; }
        public virtual DbSet<obiecteComanda> obiecteComanda { get; set; }
        public virtual DbSet<produse> produse { get; set; }
        public virtual DbSet<vanzatori> vanzatori { get; set; }
        
    }
}
