//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_CodeFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class obiecteComanda
    {
        [Key]
        public int idObiectComanda { get; set; }
        [ForeignKey("comenzi")]
        [Column(Order = 1)]
        public int idComanda { get; set; }
        [ForeignKey("produse")]
        [Column(Order = 2)]
        public int idProdus { get; set; }
        [ForeignKey("clienti")]
        [Column(Order = 3)]
        public int idClient { get; set; }
        public string situatiePlata { get; set; }
        public decimal cantitateComanda { get; set; }
    
        public virtual clienti clienti { get; set; }
        public virtual comenzi comenzi { get; set; }
        public virtual produse produse { get; set; }
    }
}
