//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_CodeFirst
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class produse
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public produse()
        {
            this.obiecteComanda = new HashSet<obiecteComanda>();
        }
        [Key]
        public int idProdus { get; set; }
        [ForeignKey("vanzatori")]
        public int idVanzator { get; set; }
        public string numeProdus { get; set; }
        public string descriereProdus { get; set; }
        public decimal pret { get; set; }
        public string unitateDeMasura { get; set; }
        public decimal cantitate { get; set; }
        public string imagine { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<obiecteComanda> obiecteComanda { get; set; }
        public virtual vanzatori vanzatori { get; set; }
    }
}
