//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class obiecteComanda
    {
        public int idObiectComanda { get; set; }
        public int idComanda { get; set; }
        public int idProdus { get; set; }
        public int idClient { get; set; }
        public string situatiePlata { get; set; }
        public decimal cantitateComanda { get; set; }
    
        public virtual clienti clienti { get; set; }
        public virtual comenzi comenzi { get; set; }
        public virtual produse produse { get; set; }
    }
}
