//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository_DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class vanzatori
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public vanzatori()
        {
            this.produs = new HashSet<produse>();
        }
    
        public int idVanzator { get; set; }
        public string numeVanzator { get; set; }
        public string prenumeVanzator { get; set; }
        public string email { get; set; }
        public string numarTelefon { get; set; }
        public bool logicalDelete { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<produse> produs { get; set; }
    }
}
