// <auto-generated />
namespace Repository_CodeFirst.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class primaIncercare_10112023 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(primaIncercare_10112023));
        
        string IMigrationMetadata.Id
        {
            get { return "202311101739495_primaIncercare_10/11/2023"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
